handlebars:
  enabled: true
  suffix: .html

spring.jackson.serialization.indent_output: true

## log settings
logging:
  file.path: ./logs/${spring.profiles.active:local}/
  level:
    com.jinair.sample: debug